sudo: required
services:
  - docker
before_install:
  - docker build -t anandahlawat/docker-react -f Dockerfile.dev .
  - gem install bundler
deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-madfocus"
  env: "MadfocusDocker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-071421208465"
  bucket_path: "docker-madfocus"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
