sudo: required
services:
  - docker
before_install:
  - docker build -t anandahlawat/docker-react -f Dockerfile.dev .
script:
  - echo "no tests!"

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  region: "ap-southeast-1"
  app: "docker-madfocus"
  env: "MadfocusDocker-env"
  bucket_name: "docker-madfocus"
  on:
    branch: master
