sudo: required
services:
  - docker
before_install:
  - docker build -t anandahlawat/docker-react -f Dockerfile.dev .
script:
  - docker run anandahlawat/docker-react npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "madfocus-docker"
  env: "MadfocusDocker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-071421208465"
  bucket_path: "madfocus-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
